image: pattacini/technical-evaluation-stack:gitpod
ports:
- port: 8080
  onOpen: notify
- port: 8888
  onOpen: notify
- port: 5901
  onOpen: notify
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
tasks:
- command: start-markserv.sh
- command: start-jupyter.sh
- command: start-vnc-session.sh
- command: tmux
