image: pattacini/technical-evaluation-stack:gitpod
ports:
- port: 8080
  onOpen: notify
- port: 8888
  onOpen: notify
- port: 6080
  onOpen: notify
tasks:
- command: cd /workspace && markserv -a 0.0.0.0 -p 8080 &
- command: cd /workspace && jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' &  
