image: ghcr.io/pattacini/technical-evaluation:gitpod
ports:
- port: 8080
  onOpen: notify
  visibility: public
- port: 8888
  onOpen: notify
  visibility: public
- port: 5901
  onOpen: notify
  visibility: public
- port: 6080
  onOpen: notify
  visibility: public
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-markserv.sh
- command: start-jupyter.sh
- command: start-vnc-session.sh
- command: >
    git config --global --unset-all user.name &&
    git config --global --unset-all user.email &&
    git config --global --unset-all credential.helper &&
    gp open /workspace/technical-evaluation/README.md
- command: gp url
